swagger: '2.0'
info:
  description: This is an Inventory Service
  version: 1.0.0
  title: Inventory API
  # put the contact info for your development or API team
  contact:
    email: mochadwi20@gmail.com

  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html

# tags are used for organizing operations
tags:
- name: developers
  description: Operations available to regular developers

paths:
  /total/stock:
    post:
      tags:
      - developers
      summary: Adds a new total stock
      operationId: addTotalStock
      description: By passing in the appropriate params, you can add new total stock
      consumes:
      - application/x-www-form-urlencoded
      parameters:
        - in: body
          name: totalstock
          description: The requested total stock body.
          schema:
            $ref: '#/definitions/TotalStockRequest'
      responses:
        201:
          description: total stock data created
          schema:
            $ref: '#/definitions/DefaultResponse'
        400:
          description: bad input parameters
          schema:
            $ref: '#/definitions/ErrorResponse'
    get:
      tags:
      - developers
      summary: Gets all total stock
      operationId: getAllTotalStock
      description: |
        A detailed all of total stock
      responses:
        200:
          description: total stock retrieved
          schema:
            $ref: '#/definitions/DefaultResponseArray'
        404:
          description: data unavailable
          schema:
            $ref: '#/definitions/ErrorResponse'

  /total/stock/{id}:
    get:
      tags:
      - developers
      summary: Gets a total stock by ID
      operationId: getTotalStockByID
      description: Get the total stock for requested ID        
      parameters:
        - name: id
          in: path
          description: Stock ID
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: total stock by id retrieved
          schema:
            $ref: '#/definitions/DefaultResponse'
        404:
          description: service unavailable
          schema:
            $ref: '#/definitions/ErrorResponse'
    put:
      tags:
      - developers
      summary: Updates a total stock by ID
      operationId: putTotalStockByID
      description: Updates the total stock for requested ID
      consumes:
        - application/x-www-form-urlencoded
      parameters:
        - name: id
          in: path
          description: Stock ID
          required: true
          schema:
            type: integer
            format: int64
        - in: body
          name: totalstock
          description: The requested total stock body.
          schema:
            $ref: '#/definitions/TotalStockRequest'
      responses:
        200:
          description: total stock by id retrieved
          schema:
            $ref: '#/definitions/DefaultResponse'
        404:
          description: service unavailable
          schema:
            $ref: '#/definitions/ErrorResponse'
    delete:
      tags:
      - developers
      summary: Deletes a total stock by ID
      operationId: deleteTotalStockByID
      description: Deletes the total stock for requested ID
      parameters:
        - name: id
          in: path
          description: Stock ID
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: total stock by id retrieved
          schema:
            $ref: '#/definitions/DefaultResponse'
        404:
          description: service unavailable
          schema:
            $ref: '#/definitions/ErrorResponse'

  /income/stock:
    post:
      tags:
      - developers
      summary: Adds a new income stock
      operationId: addIncomeStock
      description: By passing in the appropriate params, you can add new income stock
      consumes:
      - application/x-www-form-urlencoded
      parameters:
        - in: body
          name: incomestock
          description: The requested income stock body.
          schema:
            $ref: '#/definitions/IncomeStockRequest'
      responses:
        201:
          description: income stock data created
          schema:
            $ref: '#/definitions/DefaultResponse'
        400:
          description: bad input parameters
          schema:
            $ref: '#/definitions/ErrorResponse'
    get:
      tags:
      - developers
      summary: Gets all income stock
      operationId: getAllIncomeStock
      description: |
        A detailed all of income stock
      responses:
        200:
          description: income stock retrieved
          schema:
            $ref: '#/definitions/DefaultResponseArray'
        404:
          description: data unavailable
          schema:
            $ref: '#/definitions/ErrorResponse'

  /income/stock/{id}:
    get:
      tags:
      - developers
      summary: Gets a income stock by ID
      operationId: getIncomeStockByID
      description: Get the income stock for requested ID        
      parameters:
        - name: id
          in: path
          description: Stock ID
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: income stock by id retrieved
          schema:
            $ref: '#/definitions/DefaultResponse'
        404:
          description: service unavailable
          schema:
            $ref: '#/definitions/ErrorResponse'
    put:
      tags:
      - developers
      summary: Updates a income stock by ID
      operationId: putIncomeStockByID
      description: Updates the income stock for requested ID
      consumes:
        - application/x-www-form-urlencoded
      parameters:
        - name: id
          in: path
          description: Stock ID
          required: true
          schema:
            type: integer
            format: int64
        - in: body
          name: incomestock
          description: The requested income stock body.
          schema:
            $ref: '#/definitions/IncomeStockRequest'
      responses:
        200:
          description: income stock by id retrieved
          schema:
            $ref: '#/definitions/DefaultResponse'
        404:
          description: service unavailable
          schema:
            $ref: '#/definitions/ErrorResponse'
    delete:
      tags:
      - developers
      summary: Deletes a income stock by ID
      operationId: deleteIncomeStockByID
      description: Deletes the income stock for requested ID
      parameters:
        - name: id
          in: path
          description: Stock ID
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: income stock by id retrieved
          schema:
            $ref: '#/definitions/DefaultResponse'
        404:
          description: service unavailable
          schema:
            $ref: '#/definitions/ErrorResponse'

  /outcome/stock:
    post:
      tags:
      - developers
      summary: Adds a new outcome stock
      operationId: addOutcomeStock
      description: By passing in the appropriate params, you can add new outcome stock
      consumes:
      - application/x-www-form-urlencoded
      parameters:
        - in: body
          name: outcomestock
          description: The requested outcome stock body.
          schema:
            $ref: '#/definitions/OutcomeStockRequest'
      responses:
        201:
          description: outcome stock data created
          schema:
            $ref: '#/definitions/DefaultResponse'
        400:
          description: bad input parameters
          schema:
            $ref: '#/definitions/ErrorResponse'
    get:
      tags:
      - developers
      summary: Gets all outcome stock
      operationId: getAllOutcomeStock
      description: |
        A detailed all of outcome stock
      responses:
        200:
          description: outcome stock retrieved
          schema:
            $ref: '#/definitions/DefaultResponseArray'
        404:
          description: data unavailable
          schema:
            $ref: '#/definitions/ErrorResponse'

  /outcome/stock/{id}:
    get:
      tags:
      - developers
      summary: Gets a outcome stock by ID
      operationId: getOutcomeStockByID
      description: Get the outcome stock for requested ID        
      parameters:
        - name: id
          in: path
          description: Stock ID
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: outcome stock by id retrieved
          schema:
            $ref: '#/definitions/DefaultResponse'
        404:
          description: service unavailable
          schema:
            $ref: '#/definitions/ErrorResponse'
    put:
      tags:
      - developers
      summary: Updates a outcome stock by ID
      operationId: putOutcomeStockByID
      description: Updates the outcome stock for requested ID
      consumes:
        - application/x-www-form-urlencoded
      parameters:
        - name: id
          in: path
          description: Stock ID
          required: true
          schema:
            type: integer
            format: int64
        - in: body
          name: outcomestock
          description: The requested outcome stock body.
          schema:
            $ref: '#/definitions/OutcomeStockRequest'
      responses:
        200:
          description: outcome stock by id retrieved
          schema:
            $ref: '#/definitions/DefaultResponse'
        404:
          description: service unavailable
          schema:
            $ref: '#/definitions/ErrorResponse'
    delete:
      tags:
      - developers
      summary: Deletes a outcome stock by ID
      operationId: deleteOutcomeStockByID
      description: Deletes the outcome stock for requested ID
      parameters:
        - name: id
          in: path
          description: Stock ID
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: outcome stock by id retrieved
          schema:
            $ref: '#/definitions/DefaultResponse'
        404:
          description: service unavailable
          schema:
            $ref: '#/definitions/ErrorResponse'

definitions:
  ErrorResponse:
    type: object
    required:
    - requestID
    - now
    - code
    - message
    properties:
      requestID:
        type: string
        format: uuidv4
        example: "02010ce8-6878-4547-b3c0-e5592086a802"
      now:
        type: integer
        format: unix_timestamp
        example: 1511859232
      message:
        type: string
        example: "Duplicate entry"
      code:
        type: integer
        example: 400
        
  DefaultResponseArray:
    type: object
    required:
    - requestID
    - now
    - code
    - message
    - data
    properties:
      requestID:
        type: string
        format: uuidv4
        example: "02010ce8-6878-4547-b3c0-e5592086a802"
      now:
        type: integer
        format: unix_timestamp
        example: 1511859232
      message:
        type: string
        example: "OK"
      code:
        type: integer
        example: 200
      data:
        type: array
        items:
          $ref: '#/definitions/TotalStockItem'
        
  DefaultResponse:
    type: object
    required:
    - requestID
    - now
    - code
    - message
    - data
    properties:
      requestID:
        type: string
        format: uuidv4
        example: "02010ce8-6878-4547-b3c0-e5592086a802"
      now:
        type: integer
        format: unix_timestamp
        example: 1511859232
      message:
        type: string
        example: "OK"
      code:
        type: integer
        example: 200
      data:
        $ref: '#/definitions/TotalStockItem'
        
  TotalStockRequest:
    type: object
    properties:
      sku:
        type: string
        example: "SSI-D00791015-LL-BWH"
      name:
        type: string
        example: "Zalekia Plain Casual Blouse (L,Broken White)"
      size:
        type: string
        enum: [L, M, XL, S, XXX, XXL]
        example: "L"
      colour:
        type: string
        enum: [Broken White, Red, Navy, Yellow, Salem, White, Khaki, Black]
        example: "Broken White"
      currentStock:
        type: integer
        example: 100

  TotalStockItem:
    type: object
    properties:
      sku:
        type: string
        example: "SSI-D00791015-LL-BWH"
      name:
        type: string
        example: "Zalekia Plain Casual Blouse (L,Broken White)"
      currentStock:
        type: integer
        example: 100
      createdAt:
        type: integer
        format: unix_timestamp
        example: 1511859232
      updatedAt:
        type: integer
        format: unix_timestamp
        example: 1511859233
      deletedAt:
        type: integer
        format: unix_timestamp
        example: 1511859233

  IncomeStockRequest:
    type: object
    properties:
      sku:
        type: string
        example: "SSI-D00791015-LL-BWH"
      name:
        type: string
        example: "Zalekia Plain Casual Blouse"
      orderAmount:
        type: integer
        example: 100
      amountReceived:
        type: integer
        example: 100
      purchasePrice:
        type: string
        example: 74000
      note:
        type: string
        example: "2018/01/06 terima 47; Masih Menunggu"

  IncomeStockItem:
    type: object
    properties:
      time:
        type: unix_timestamp
        example: 1511859233
      sku:
        type: string
        example: "SSI-D00791015-LL-BWH"
      name:
        type: string
        example: "Zalekia Plain Casual Blouse"
      orderAmount:
        type: integer
        example: 100
      amountReceived:
        type: integer
        example: 100
      purchasePrice:
        type: string
        example: 74000
      totalPrice:
        type: integer
        example: 74000
      receiptNumber:
        type: string
        example: "20180102-69539"
      note:
        type: string
        example: "2018/01/06 terima 47; Masih Menunggu"

  OutcomeStockRequest:
    type: object
    properties:
      sku:
        type: string
        example: "SSI-D00791015-LL-BWH"
      name:
        type: string
        example: "Zalekia Plain Casual Blouse"
      amountDelivered:
        type: integer
        example: 100
      sellPrice:
        type: string
        example: 74000
      note:
        type: string
        example: "Pesanan ID-20180108-548167"

  OutcomeStockItem:
    type: object
    properties:
      time:
        type: unix_timestamp
        example: 1511859233
      sku:
        type: string
        example: "SSI-D00791015-LL-BWH"
      name:
        type: string
        example: "Zalekia Plain Casual Blouse"
      amountDelivered:
        type: integer
        example: 100
      sellPrice:
        type: string
        example: 74000
      totalPrice:
        type: integer
        example: 74000
      note:
        type: string
        example: "Pesanan ID-20180108-548167"

schemes:
 - https
host: localhost
basePath: /api/v1/