package models

import (
	"fmt"
	"time"

	"github.com/jinzhu/gorm"
)

// ===== BEGIN of all query sets

// ===== BEGIN of query set OutcomeStockRequestQuerySet

// OutcomeStockRequestQuerySet is an queryset type for OutcomeStockRequest
type OutcomeStockRequestQuerySet struct {
	db *gorm.DB
}

// NewOutcomeStockRequestQuerySet constructs new OutcomeStockRequestQuerySet
func NewOutcomeStockRequestQuerySet(db *gorm.DB) OutcomeStockRequestQuerySet {
	return OutcomeStockRequestQuerySet{
		db: db.Model(&OutcomeStockRequest{}),
	}
}

func (qs OutcomeStockRequestQuerySet) w(db *gorm.DB) OutcomeStockRequestQuerySet {
	return NewOutcomeStockRequestQuerySet(db)
}

// All is an autogenerated method
// nolint: dupl
func (qs OutcomeStockRequestQuerySet) All(ret *[]OutcomeStockRequest) error {
	return qs.db.Find(ret).Error
}

// AmountDeliveredEq is an autogenerated method
// nolint: dupl
func (qs OutcomeStockRequestQuerySet) AmountDeliveredEq(amountDelivered uint) OutcomeStockRequestQuerySet {
	return qs.w(qs.db.Where("amount_delivered = ?", amountDelivered))
}

// AmountDeliveredGt is an autogenerated method
// nolint: dupl
func (qs OutcomeStockRequestQuerySet) AmountDeliveredGt(amountDelivered uint) OutcomeStockRequestQuerySet {
	return qs.w(qs.db.Where("amount_delivered > ?", amountDelivered))
}

// AmountDeliveredGte is an autogenerated method
// nolint: dupl
func (qs OutcomeStockRequestQuerySet) AmountDeliveredGte(amountDelivered uint) OutcomeStockRequestQuerySet {
	return qs.w(qs.db.Where("amount_delivered >= ?", amountDelivered))
}

// AmountDeliveredIn is an autogenerated method
// nolint: dupl
func (qs OutcomeStockRequestQuerySet) AmountDeliveredIn(amountDelivered uint, amountDeliveredRest ...uint) OutcomeStockRequestQuerySet {
	iArgs := []interface{}{amountDelivered}
	for _, arg := range amountDeliveredRest {
		iArgs = append(iArgs, arg)
	}
	return qs.w(qs.db.Where("amount_delivered IN (?)", iArgs))
}

// AmountDeliveredLt is an autogenerated method
// nolint: dupl
func (qs OutcomeStockRequestQuerySet) AmountDeliveredLt(amountDelivered uint) OutcomeStockRequestQuerySet {
	return qs.w(qs.db.Where("amount_delivered < ?", amountDelivered))
}

// AmountDeliveredLte is an autogenerated method
// nolint: dupl
func (qs OutcomeStockRequestQuerySet) AmountDeliveredLte(amountDelivered uint) OutcomeStockRequestQuerySet {
	return qs.w(qs.db.Where("amount_delivered <= ?", amountDelivered))
}

// AmountDeliveredNe is an autogenerated method
// nolint: dupl
func (qs OutcomeStockRequestQuerySet) AmountDeliveredNe(amountDelivered uint) OutcomeStockRequestQuerySet {
	return qs.w(qs.db.Where("amount_delivered != ?", amountDelivered))
}

// AmountDeliveredNotIn is an autogenerated method
// nolint: dupl
func (qs OutcomeStockRequestQuerySet) AmountDeliveredNotIn(amountDelivered uint, amountDeliveredRest ...uint) OutcomeStockRequestQuerySet {
	iArgs := []interface{}{amountDelivered}
	for _, arg := range amountDeliveredRest {
		iArgs = append(iArgs, arg)
	}
	return qs.w(qs.db.Where("amount_delivered NOT IN (?)", iArgs))
}

// Count is an autogenerated method
// nolint: dupl
func (qs OutcomeStockRequestQuerySet) Count() (int, error) {
	var count int
	err := qs.db.Count(&count).Error
	return count, err
}

// Create is an autogenerated method
// nolint: dupl
func (o *OutcomeStockRequest) Create(db *gorm.DB) error {
	return db.Create(o).Error
}

// CreatedAtEq is an autogenerated method
// nolint: dupl
func (qs OutcomeStockRequestQuerySet) CreatedAtEq(createdAt time.Time) OutcomeStockRequestQuerySet {
	return qs.w(qs.db.Where("created_at = ?", createdAt))
}

// CreatedAtGt is an autogenerated method
// nolint: dupl
func (qs OutcomeStockRequestQuerySet) CreatedAtGt(createdAt time.Time) OutcomeStockRequestQuerySet {
	return qs.w(qs.db.Where("created_at > ?", createdAt))
}

// CreatedAtGte is an autogenerated method
// nolint: dupl
func (qs OutcomeStockRequestQuerySet) CreatedAtGte(createdAt time.Time) OutcomeStockRequestQuerySet {
	return qs.w(qs.db.Where("created_at >= ?", createdAt))
}

// CreatedAtLt is an autogenerated method
// nolint: dupl
func (qs OutcomeStockRequestQuerySet) CreatedAtLt(createdAt time.Time) OutcomeStockRequestQuerySet {
	return qs.w(qs.db.Where("created_at < ?", createdAt))
}

// CreatedAtLte is an autogenerated method
// nolint: dupl
func (qs OutcomeStockRequestQuerySet) CreatedAtLte(createdAt time.Time) OutcomeStockRequestQuerySet {
	return qs.w(qs.db.Where("created_at <= ?", createdAt))
}

// CreatedAtNe is an autogenerated method
// nolint: dupl
func (qs OutcomeStockRequestQuerySet) CreatedAtNe(createdAt time.Time) OutcomeStockRequestQuerySet {
	return qs.w(qs.db.Where("created_at != ?", createdAt))
}

// Delete is an autogenerated method
// nolint: dupl
func (qs OutcomeStockRequestQuerySet) Delete() error {
	return qs.db.Delete(OutcomeStockRequest{}).Error
}

// Delete is an autogenerated method
// nolint: dupl
func (o *OutcomeStockRequest) Delete(db *gorm.DB) error {
	return db.Delete(o).Error
}

// DeletedAtEq is an autogenerated method
// nolint: dupl
func (qs OutcomeStockRequestQuerySet) DeletedAtEq(deletedAt time.Time) OutcomeStockRequestQuerySet {
	return qs.w(qs.db.Where("deleted_at = ?", deletedAt))
}

// DeletedAtGt is an autogenerated method
// nolint: dupl
func (qs OutcomeStockRequestQuerySet) DeletedAtGt(deletedAt time.Time) OutcomeStockRequestQuerySet {
	return qs.w(qs.db.Where("deleted_at > ?", deletedAt))
}

// DeletedAtGte is an autogenerated method
// nolint: dupl
func (qs OutcomeStockRequestQuerySet) DeletedAtGte(deletedAt time.Time) OutcomeStockRequestQuerySet {
	return qs.w(qs.db.Where("deleted_at >= ?", deletedAt))
}

// DeletedAtIsNotNull is an autogenerated method
// nolint: dupl
func (qs OutcomeStockRequestQuerySet) DeletedAtIsNotNull() OutcomeStockRequestQuerySet {
	return qs.w(qs.db.Where("deleted_at IS NOT NULL"))
}

// DeletedAtIsNull is an autogenerated method
// nolint: dupl
func (qs OutcomeStockRequestQuerySet) DeletedAtIsNull() OutcomeStockRequestQuerySet {
	return qs.w(qs.db.Where("deleted_at IS NULL"))
}

// DeletedAtLt is an autogenerated method
// nolint: dupl
func (qs OutcomeStockRequestQuerySet) DeletedAtLt(deletedAt time.Time) OutcomeStockRequestQuerySet {
	return qs.w(qs.db.Where("deleted_at < ?", deletedAt))
}

// DeletedAtLte is an autogenerated method
// nolint: dupl
func (qs OutcomeStockRequestQuerySet) DeletedAtLte(deletedAt time.Time) OutcomeStockRequestQuerySet {
	return qs.w(qs.db.Where("deleted_at <= ?", deletedAt))
}

// DeletedAtNe is an autogenerated method
// nolint: dupl
func (qs OutcomeStockRequestQuerySet) DeletedAtNe(deletedAt time.Time) OutcomeStockRequestQuerySet {
	return qs.w(qs.db.Where("deleted_at != ?", deletedAt))
}

// GetUpdater is an autogenerated method
// nolint: dupl
func (qs OutcomeStockRequestQuerySet) GetUpdater() OutcomeStockRequestUpdater {
	return NewOutcomeStockRequestUpdater(qs.db)
}

// IDEq is an autogenerated method
// nolint: dupl
func (qs OutcomeStockRequestQuerySet) IDEq(ID uint) OutcomeStockRequestQuerySet {
	return qs.w(qs.db.Where("id = ?", ID))
}

// IDGt is an autogenerated method
// nolint: dupl
func (qs OutcomeStockRequestQuerySet) IDGt(ID uint) OutcomeStockRequestQuerySet {
	return qs.w(qs.db.Where("id > ?", ID))
}

// IDGte is an autogenerated method
// nolint: dupl
func (qs OutcomeStockRequestQuerySet) IDGte(ID uint) OutcomeStockRequestQuerySet {
	return qs.w(qs.db.Where("id >= ?", ID))
}

// IDIn is an autogenerated method
// nolint: dupl
func (qs OutcomeStockRequestQuerySet) IDIn(ID uint, IDRest ...uint) OutcomeStockRequestQuerySet {
	iArgs := []interface{}{ID}
	for _, arg := range IDRest {
		iArgs = append(iArgs, arg)
	}
	return qs.w(qs.db.Where("id IN (?)", iArgs))
}

// IDLt is an autogenerated method
// nolint: dupl
func (qs OutcomeStockRequestQuerySet) IDLt(ID uint) OutcomeStockRequestQuerySet {
	return qs.w(qs.db.Where("id < ?", ID))
}

// IDLte is an autogenerated method
// nolint: dupl
func (qs OutcomeStockRequestQuerySet) IDLte(ID uint) OutcomeStockRequestQuerySet {
	return qs.w(qs.db.Where("id <= ?", ID))
}

// IDNe is an autogenerated method
// nolint: dupl
func (qs OutcomeStockRequestQuerySet) IDNe(ID uint) OutcomeStockRequestQuerySet {
	return qs.w(qs.db.Where("id != ?", ID))
}

// IDNotIn is an autogenerated method
// nolint: dupl
func (qs OutcomeStockRequestQuerySet) IDNotIn(ID uint, IDRest ...uint) OutcomeStockRequestQuerySet {
	iArgs := []interface{}{ID}
	for _, arg := range IDRest {
		iArgs = append(iArgs, arg)
	}
	return qs.w(qs.db.Where("id NOT IN (?)", iArgs))
}

// Limit is an autogenerated method
// nolint: dupl
func (qs OutcomeStockRequestQuerySet) Limit(limit int) OutcomeStockRequestQuerySet {
	return qs.w(qs.db.Limit(limit))
}

// NameEq is an autogenerated method
// nolint: dupl
func (qs OutcomeStockRequestQuerySet) NameEq(name string) OutcomeStockRequestQuerySet {
	return qs.w(qs.db.Where("name = ?", name))
}

// NameIn is an autogenerated method
// nolint: dupl
func (qs OutcomeStockRequestQuerySet) NameIn(name string, nameRest ...string) OutcomeStockRequestQuerySet {
	iArgs := []interface{}{name}
	for _, arg := range nameRest {
		iArgs = append(iArgs, arg)
	}
	return qs.w(qs.db.Where("name IN (?)", iArgs))
}

// NameNe is an autogenerated method
// nolint: dupl
func (qs OutcomeStockRequestQuerySet) NameNe(name string) OutcomeStockRequestQuerySet {
	return qs.w(qs.db.Where("name != ?", name))
}

// NameNotIn is an autogenerated method
// nolint: dupl
func (qs OutcomeStockRequestQuerySet) NameNotIn(name string, nameRest ...string) OutcomeStockRequestQuerySet {
	iArgs := []interface{}{name}
	for _, arg := range nameRest {
		iArgs = append(iArgs, arg)
	}
	return qs.w(qs.db.Where("name NOT IN (?)", iArgs))
}

// NoteEq is an autogenerated method
// nolint: dupl
func (qs OutcomeStockRequestQuerySet) NoteEq(note string) OutcomeStockRequestQuerySet {
	return qs.w(qs.db.Where("note = ?", note))
}

// NoteIn is an autogenerated method
// nolint: dupl
func (qs OutcomeStockRequestQuerySet) NoteIn(note string, noteRest ...string) OutcomeStockRequestQuerySet {
	iArgs := []interface{}{note}
	for _, arg := range noteRest {
		iArgs = append(iArgs, arg)
	}
	return qs.w(qs.db.Where("note IN (?)", iArgs))
}

// NoteNe is an autogenerated method
// nolint: dupl
func (qs OutcomeStockRequestQuerySet) NoteNe(note string) OutcomeStockRequestQuerySet {
	return qs.w(qs.db.Where("note != ?", note))
}

// NoteNotIn is an autogenerated method
// nolint: dupl
func (qs OutcomeStockRequestQuerySet) NoteNotIn(note string, noteRest ...string) OutcomeStockRequestQuerySet {
	iArgs := []interface{}{note}
	for _, arg := range noteRest {
		iArgs = append(iArgs, arg)
	}
	return qs.w(qs.db.Where("note NOT IN (?)", iArgs))
}

// One is used to retrieve one result. It returns gorm.ErrRecordNotFound
// if nothing was fetched
func (qs OutcomeStockRequestQuerySet) One(ret *OutcomeStockRequest) error {
	return qs.db.First(ret).Error
}

// OrderAscByAmountDelivered is an autogenerated method
// nolint: dupl
func (qs OutcomeStockRequestQuerySet) OrderAscByAmountDelivered() OutcomeStockRequestQuerySet {
	return qs.w(qs.db.Order("amount_delivered ASC"))
}

// OrderAscByCreatedAt is an autogenerated method
// nolint: dupl
func (qs OutcomeStockRequestQuerySet) OrderAscByCreatedAt() OutcomeStockRequestQuerySet {
	return qs.w(qs.db.Order("created_at ASC"))
}

// OrderAscByDeletedAt is an autogenerated method
// nolint: dupl
func (qs OutcomeStockRequestQuerySet) OrderAscByDeletedAt() OutcomeStockRequestQuerySet {
	return qs.w(qs.db.Order("deleted_at ASC"))
}

// OrderAscByID is an autogenerated method
// nolint: dupl
func (qs OutcomeStockRequestQuerySet) OrderAscByID() OutcomeStockRequestQuerySet {
	return qs.w(qs.db.Order("id ASC"))
}

// OrderAscBySellPrice is an autogenerated method
// nolint: dupl
func (qs OutcomeStockRequestQuerySet) OrderAscBySellPrice() OutcomeStockRequestQuerySet {
	return qs.w(qs.db.Order("sell_price ASC"))
}

// OrderAscByTime is an autogenerated method
// nolint: dupl
func (qs OutcomeStockRequestQuerySet) OrderAscByTime() OutcomeStockRequestQuerySet {
	return qs.w(qs.db.Order("time ASC"))
}

// OrderAscByTotalPrice is an autogenerated method
// nolint: dupl
func (qs OutcomeStockRequestQuerySet) OrderAscByTotalPrice() OutcomeStockRequestQuerySet {
	return qs.w(qs.db.Order("total_price ASC"))
}

// OrderAscByUpdatedAt is an autogenerated method
// nolint: dupl
func (qs OutcomeStockRequestQuerySet) OrderAscByUpdatedAt() OutcomeStockRequestQuerySet {
	return qs.w(qs.db.Order("updated_at ASC"))
}

// OrderDescByAmountDelivered is an autogenerated method
// nolint: dupl
func (qs OutcomeStockRequestQuerySet) OrderDescByAmountDelivered() OutcomeStockRequestQuerySet {
	return qs.w(qs.db.Order("amount_delivered DESC"))
}

// OrderDescByCreatedAt is an autogenerated method
// nolint: dupl
func (qs OutcomeStockRequestQuerySet) OrderDescByCreatedAt() OutcomeStockRequestQuerySet {
	return qs.w(qs.db.Order("created_at DESC"))
}

// OrderDescByDeletedAt is an autogenerated method
// nolint: dupl
func (qs OutcomeStockRequestQuerySet) OrderDescByDeletedAt() OutcomeStockRequestQuerySet {
	return qs.w(qs.db.Order("deleted_at DESC"))
}

// OrderDescByID is an autogenerated method
// nolint: dupl
func (qs OutcomeStockRequestQuerySet) OrderDescByID() OutcomeStockRequestQuerySet {
	return qs.w(qs.db.Order("id DESC"))
}

// OrderDescBySellPrice is an autogenerated method
// nolint: dupl
func (qs OutcomeStockRequestQuerySet) OrderDescBySellPrice() OutcomeStockRequestQuerySet {
	return qs.w(qs.db.Order("sell_price DESC"))
}

// OrderDescByTime is an autogenerated method
// nolint: dupl
func (qs OutcomeStockRequestQuerySet) OrderDescByTime() OutcomeStockRequestQuerySet {
	return qs.w(qs.db.Order("time DESC"))
}

// OrderDescByTotalPrice is an autogenerated method
// nolint: dupl
func (qs OutcomeStockRequestQuerySet) OrderDescByTotalPrice() OutcomeStockRequestQuerySet {
	return qs.w(qs.db.Order("total_price DESC"))
}

// OrderDescByUpdatedAt is an autogenerated method
// nolint: dupl
func (qs OutcomeStockRequestQuerySet) OrderDescByUpdatedAt() OutcomeStockRequestQuerySet {
	return qs.w(qs.db.Order("updated_at DESC"))
}

// SKUEq is an autogenerated method
// nolint: dupl
func (qs OutcomeStockRequestQuerySet) SKUEq(sKU string) OutcomeStockRequestQuerySet {
	return qs.w(qs.db.Where("sku = ?", sKU))
}

// SKUIn is an autogenerated method
// nolint: dupl
func (qs OutcomeStockRequestQuerySet) SKUIn(sKU string, sKURest ...string) OutcomeStockRequestQuerySet {
	iArgs := []interface{}{sKU}
	for _, arg := range sKURest {
		iArgs = append(iArgs, arg)
	}
	return qs.w(qs.db.Where("sku IN (?)", iArgs))
}

// SKUNe is an autogenerated method
// nolint: dupl
func (qs OutcomeStockRequestQuerySet) SKUNe(sKU string) OutcomeStockRequestQuerySet {
	return qs.w(qs.db.Where("sku != ?", sKU))
}

// SKUNotIn is an autogenerated method
// nolint: dupl
func (qs OutcomeStockRequestQuerySet) SKUNotIn(sKU string, sKURest ...string) OutcomeStockRequestQuerySet {
	iArgs := []interface{}{sKU}
	for _, arg := range sKURest {
		iArgs = append(iArgs, arg)
	}
	return qs.w(qs.db.Where("sku NOT IN (?)", iArgs))
}

// SellPriceEq is an autogenerated method
// nolint: dupl
func (qs OutcomeStockRequestQuerySet) SellPriceEq(sellPrice uint) OutcomeStockRequestQuerySet {
	return qs.w(qs.db.Where("sell_price = ?", sellPrice))
}

// SellPriceGt is an autogenerated method
// nolint: dupl
func (qs OutcomeStockRequestQuerySet) SellPriceGt(sellPrice uint) OutcomeStockRequestQuerySet {
	return qs.w(qs.db.Where("sell_price > ?", sellPrice))
}

// SellPriceGte is an autogenerated method
// nolint: dupl
func (qs OutcomeStockRequestQuerySet) SellPriceGte(sellPrice uint) OutcomeStockRequestQuerySet {
	return qs.w(qs.db.Where("sell_price >= ?", sellPrice))
}

// SellPriceIn is an autogenerated method
// nolint: dupl
func (qs OutcomeStockRequestQuerySet) SellPriceIn(sellPrice uint, sellPriceRest ...uint) OutcomeStockRequestQuerySet {
	iArgs := []interface{}{sellPrice}
	for _, arg := range sellPriceRest {
		iArgs = append(iArgs, arg)
	}
	return qs.w(qs.db.Where("sell_price IN (?)", iArgs))
}

// SellPriceLt is an autogenerated method
// nolint: dupl
func (qs OutcomeStockRequestQuerySet) SellPriceLt(sellPrice uint) OutcomeStockRequestQuerySet {
	return qs.w(qs.db.Where("sell_price < ?", sellPrice))
}

// SellPriceLte is an autogenerated method
// nolint: dupl
func (qs OutcomeStockRequestQuerySet) SellPriceLte(sellPrice uint) OutcomeStockRequestQuerySet {
	return qs.w(qs.db.Where("sell_price <= ?", sellPrice))
}

// SellPriceNe is an autogenerated method
// nolint: dupl
func (qs OutcomeStockRequestQuerySet) SellPriceNe(sellPrice uint) OutcomeStockRequestQuerySet {
	return qs.w(qs.db.Where("sell_price != ?", sellPrice))
}

// SellPriceNotIn is an autogenerated method
// nolint: dupl
func (qs OutcomeStockRequestQuerySet) SellPriceNotIn(sellPrice uint, sellPriceRest ...uint) OutcomeStockRequestQuerySet {
	iArgs := []interface{}{sellPrice}
	for _, arg := range sellPriceRest {
		iArgs = append(iArgs, arg)
	}
	return qs.w(qs.db.Where("sell_price NOT IN (?)", iArgs))
}

// SetAmountDelivered is an autogenerated method
// nolint: dupl
func (u OutcomeStockRequestUpdater) SetAmountDelivered(amountDelivered uint) OutcomeStockRequestUpdater {
	u.fields[string(OutcomeStockRequestDBSchema.AmountDelivered)] = amountDelivered
	return u
}

// SetCreatedAt is an autogenerated method
// nolint: dupl
func (u OutcomeStockRequestUpdater) SetCreatedAt(createdAt time.Time) OutcomeStockRequestUpdater {
	u.fields[string(OutcomeStockRequestDBSchema.CreatedAt)] = createdAt
	return u
}

// SetDeletedAt is an autogenerated method
// nolint: dupl
func (u OutcomeStockRequestUpdater) SetDeletedAt(deletedAt *time.Time) OutcomeStockRequestUpdater {
	u.fields[string(OutcomeStockRequestDBSchema.DeletedAt)] = deletedAt
	return u
}

// SetID is an autogenerated method
// nolint: dupl
func (u OutcomeStockRequestUpdater) SetID(ID uint) OutcomeStockRequestUpdater {
	u.fields[string(OutcomeStockRequestDBSchema.ID)] = ID
	return u
}

// SetName is an autogenerated method
// nolint: dupl
func (u OutcomeStockRequestUpdater) SetName(name string) OutcomeStockRequestUpdater {
	u.fields[string(OutcomeStockRequestDBSchema.Name)] = name
	return u
}

// SetNote is an autogenerated method
// nolint: dupl
func (u OutcomeStockRequestUpdater) SetNote(note string) OutcomeStockRequestUpdater {
	u.fields[string(OutcomeStockRequestDBSchema.Note)] = note
	return u
}

// SetSKU is an autogenerated method
// nolint: dupl
func (u OutcomeStockRequestUpdater) SetSKU(sKU string) OutcomeStockRequestUpdater {
	u.fields[string(OutcomeStockRequestDBSchema.SKU)] = sKU
	return u
}

// SetSellPrice is an autogenerated method
// nolint: dupl
func (u OutcomeStockRequestUpdater) SetSellPrice(sellPrice uint) OutcomeStockRequestUpdater {
	u.fields[string(OutcomeStockRequestDBSchema.SellPrice)] = sellPrice
	return u
}

// SetTime is an autogenerated method
// nolint: dupl
func (u OutcomeStockRequestUpdater) SetTime(time time.Time) OutcomeStockRequestUpdater {
	u.fields[string(OutcomeStockRequestDBSchema.Time)] = time
	return u
}

// SetTotalPrice is an autogenerated method
// nolint: dupl
func (u OutcomeStockRequestUpdater) SetTotalPrice(totalPrice uint) OutcomeStockRequestUpdater {
	u.fields[string(OutcomeStockRequestDBSchema.TotalPrice)] = totalPrice
	return u
}

// SetUpdatedAt is an autogenerated method
// nolint: dupl
func (u OutcomeStockRequestUpdater) SetUpdatedAt(updatedAt time.Time) OutcomeStockRequestUpdater {
	u.fields[string(OutcomeStockRequestDBSchema.UpdatedAt)] = updatedAt
	return u
}

// TimeEq is an autogenerated method
// nolint: dupl
func (qs OutcomeStockRequestQuerySet) TimeEq(time time.Time) OutcomeStockRequestQuerySet {
	return qs.w(qs.db.Where("time = ?", time))
}

// TimeGt is an autogenerated method
// nolint: dupl
func (qs OutcomeStockRequestQuerySet) TimeGt(time time.Time) OutcomeStockRequestQuerySet {
	return qs.w(qs.db.Where("time > ?", time))
}

// TimeGte is an autogenerated method
// nolint: dupl
func (qs OutcomeStockRequestQuerySet) TimeGte(time time.Time) OutcomeStockRequestQuerySet {
	return qs.w(qs.db.Where("time >= ?", time))
}

// TimeLt is an autogenerated method
// nolint: dupl
func (qs OutcomeStockRequestQuerySet) TimeLt(time time.Time) OutcomeStockRequestQuerySet {
	return qs.w(qs.db.Where("time < ?", time))
}

// TimeLte is an autogenerated method
// nolint: dupl
func (qs OutcomeStockRequestQuerySet) TimeLte(time time.Time) OutcomeStockRequestQuerySet {
	return qs.w(qs.db.Where("time <= ?", time))
}

// TimeNe is an autogenerated method
// nolint: dupl
func (qs OutcomeStockRequestQuerySet) TimeNe(time time.Time) OutcomeStockRequestQuerySet {
	return qs.w(qs.db.Where("time != ?", time))
}

// TotalPriceEq is an autogenerated method
// nolint: dupl
func (qs OutcomeStockRequestQuerySet) TotalPriceEq(totalPrice uint) OutcomeStockRequestQuerySet {
	return qs.w(qs.db.Where("total_price = ?", totalPrice))
}

// TotalPriceGt is an autogenerated method
// nolint: dupl
func (qs OutcomeStockRequestQuerySet) TotalPriceGt(totalPrice uint) OutcomeStockRequestQuerySet {
	return qs.w(qs.db.Where("total_price > ?", totalPrice))
}

// TotalPriceGte is an autogenerated method
// nolint: dupl
func (qs OutcomeStockRequestQuerySet) TotalPriceGte(totalPrice uint) OutcomeStockRequestQuerySet {
	return qs.w(qs.db.Where("total_price >= ?", totalPrice))
}

// TotalPriceIn is an autogenerated method
// nolint: dupl
func (qs OutcomeStockRequestQuerySet) TotalPriceIn(totalPrice uint, totalPriceRest ...uint) OutcomeStockRequestQuerySet {
	iArgs := []interface{}{totalPrice}
	for _, arg := range totalPriceRest {
		iArgs = append(iArgs, arg)
	}
	return qs.w(qs.db.Where("total_price IN (?)", iArgs))
}

// TotalPriceLt is an autogenerated method
// nolint: dupl
func (qs OutcomeStockRequestQuerySet) TotalPriceLt(totalPrice uint) OutcomeStockRequestQuerySet {
	return qs.w(qs.db.Where("total_price < ?", totalPrice))
}

// TotalPriceLte is an autogenerated method
// nolint: dupl
func (qs OutcomeStockRequestQuerySet) TotalPriceLte(totalPrice uint) OutcomeStockRequestQuerySet {
	return qs.w(qs.db.Where("total_price <= ?", totalPrice))
}

// TotalPriceNe is an autogenerated method
// nolint: dupl
func (qs OutcomeStockRequestQuerySet) TotalPriceNe(totalPrice uint) OutcomeStockRequestQuerySet {
	return qs.w(qs.db.Where("total_price != ?", totalPrice))
}

// TotalPriceNotIn is an autogenerated method
// nolint: dupl
func (qs OutcomeStockRequestQuerySet) TotalPriceNotIn(totalPrice uint, totalPriceRest ...uint) OutcomeStockRequestQuerySet {
	iArgs := []interface{}{totalPrice}
	for _, arg := range totalPriceRest {
		iArgs = append(iArgs, arg)
	}
	return qs.w(qs.db.Where("total_price NOT IN (?)", iArgs))
}

// Update is an autogenerated method
// nolint: dupl
func (u OutcomeStockRequestUpdater) Update() error {
	return u.db.Updates(u.fields).Error
}

// UpdateNum is an autogenerated method
// nolint: dupl
func (u OutcomeStockRequestUpdater) UpdateNum() (int64, error) {
	db := u.db.Updates(u.fields)
	return db.RowsAffected, db.Error
}

// UpdatedAtEq is an autogenerated method
// nolint: dupl
func (qs OutcomeStockRequestQuerySet) UpdatedAtEq(updatedAt time.Time) OutcomeStockRequestQuerySet {
	return qs.w(qs.db.Where("updated_at = ?", updatedAt))
}

// UpdatedAtGt is an autogenerated method
// nolint: dupl
func (qs OutcomeStockRequestQuerySet) UpdatedAtGt(updatedAt time.Time) OutcomeStockRequestQuerySet {
	return qs.w(qs.db.Where("updated_at > ?", updatedAt))
}

// UpdatedAtGte is an autogenerated method
// nolint: dupl
func (qs OutcomeStockRequestQuerySet) UpdatedAtGte(updatedAt time.Time) OutcomeStockRequestQuerySet {
	return qs.w(qs.db.Where("updated_at >= ?", updatedAt))
}

// UpdatedAtLt is an autogenerated method
// nolint: dupl
func (qs OutcomeStockRequestQuerySet) UpdatedAtLt(updatedAt time.Time) OutcomeStockRequestQuerySet {
	return qs.w(qs.db.Where("updated_at < ?", updatedAt))
}

// UpdatedAtLte is an autogenerated method
// nolint: dupl
func (qs OutcomeStockRequestQuerySet) UpdatedAtLte(updatedAt time.Time) OutcomeStockRequestQuerySet {
	return qs.w(qs.db.Where("updated_at <= ?", updatedAt))
}

// UpdatedAtNe is an autogenerated method
// nolint: dupl
func (qs OutcomeStockRequestQuerySet) UpdatedAtNe(updatedAt time.Time) OutcomeStockRequestQuerySet {
	return qs.w(qs.db.Where("updated_at != ?", updatedAt))
}

// JoinClause
func (qs OutcomeStockRequestQuerySet) JoinClause(fromDate string, toDate string) OutcomeStockRequestQuerySet {
	return qs.w(qs.db.
		Select("outcome_stock_requests.sku, outcome_stock_requests.name, outcome_stock_requests.amount_delivered, outcome_stock_requests.sell_price, outcome_stock_requests.total_price, income_stock_requests.purchase_price, outcome_stock_requests.total_price - (income_stock_requests.purchase_price * outcome_stock_requests.amount_delivered) as profit").
		Joins("INNER JOIN income_stock_requests ON outcome_stock_requests.sku = income_stock_requests.sku").
		Where("outcome_stock_requests.time BETWEEN ? AND ?", fromDate, toDate))
}

// ===== END of query set OutcomeStockRequestQuerySet

// ===== BEGIN of OutcomeStockRequest modifiers

type outcomeStockRequestDBSchemaField string

func (f outcomeStockRequestDBSchemaField) String() string {
	return string(f)
}

// OutcomeStockRequestDBSchema stores db field names of OutcomeStockRequest
var OutcomeStockRequestDBSchema = struct {
	Time            outcomeStockRequestDBSchemaField
	ID              outcomeStockRequestDBSchemaField
	SKU             outcomeStockRequestDBSchemaField
	Name            outcomeStockRequestDBSchemaField
	CreatedAt       outcomeStockRequestDBSchemaField
	UpdatedAt       outcomeStockRequestDBSchemaField
	DeletedAt       outcomeStockRequestDBSchemaField
	AmountDelivered outcomeStockRequestDBSchemaField
	SellPrice       outcomeStockRequestDBSchemaField
	TotalPrice      outcomeStockRequestDBSchemaField
	Note            outcomeStockRequestDBSchemaField
}{

	Time:            outcomeStockRequestDBSchemaField("time"),
	ID:              outcomeStockRequestDBSchemaField("id"),
	SKU:             outcomeStockRequestDBSchemaField("sku"),
	Name:            outcomeStockRequestDBSchemaField("name"),
	CreatedAt:       outcomeStockRequestDBSchemaField("created_at"),
	UpdatedAt:       outcomeStockRequestDBSchemaField("updated_at"),
	DeletedAt:       outcomeStockRequestDBSchemaField("deleted_at"),
	AmountDelivered: outcomeStockRequestDBSchemaField("amount_delivered"),
	SellPrice:       outcomeStockRequestDBSchemaField("sell_price"),
	TotalPrice:      outcomeStockRequestDBSchemaField("total_price"),
	Note:            outcomeStockRequestDBSchemaField("note"),
}

// Update updates OutcomeStockRequest fields by primary key
func (o *OutcomeStockRequest) Update(db *gorm.DB, fields ...outcomeStockRequestDBSchemaField) error {
	dbNameToFieldName := map[string]interface{}{
		"time":             o.Time,
		"id":               o.ID,
		"sku":              o.SKU,
		"name":             o.Name,
		"created_at":       o.CreatedAt,
		"updated_at":       o.UpdatedAt,
		"deleted_at":       o.DeletedAt,
		"amount_delivered": o.AmountDelivered,
		"sell_price":       o.SellPrice,
		"total_price":      o.TotalPrice,
		"note":             o.Note,
	}
	u := map[string]interface{}{}
	for _, f := range fields {
		fs := f.String()
		u[fs] = dbNameToFieldName[fs]
	}
	if err := db.Model(o).Updates(u).Error; err != nil {
		if err == gorm.ErrRecordNotFound {
			return err
		}

		return fmt.Errorf("can't update OutcomeStockRequest %v fields %v: %s",
			o, fields, err)
	}

	return nil
}

// OutcomeStockRequestUpdater is an OutcomeStockRequest updates manager
type OutcomeStockRequestUpdater struct {
	fields map[string]interface{}
	db     *gorm.DB
}

// NewOutcomeStockRequestUpdater creates new OutcomeStockRequest updater
func NewOutcomeStockRequestUpdater(db *gorm.DB) OutcomeStockRequestUpdater {
	return OutcomeStockRequestUpdater{
		fields: map[string]interface{}{},
		db:     db.Model(&OutcomeStockRequest{}),
	}
}

// ===== END of OutcomeStockRequest modifiers

// ===== END of all query sets
